# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LTPractice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LTPractice
  pod 'SnapKit'
  pod 'Masonry', '~> 1.1.0'
  pod 'ReactiveCocoa'
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'LTPracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LTPracticeUITests' do
    # Pods for testing
  end

end
